# Generated by Django 3.2.21 on 2023-09-24 14:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('adress_1', models.CharField(max_length=255, verbose_name='Street Adress')),
                ('city_town', models.CharField(max_length=255, verbose_name='City/Town')),
                ('province_state', models.CharField(max_length=255, verbose_name='State/Province/Region')),
                ('post_code', models.CharField(max_length=255, verbose_name='Postal Code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
