# Generated by Django 3.2.21 on 2023-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
