# Generated by Django 3.2.21 on 2023-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230924_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(default='', max_length=30, verbose_name='VAT'),
            preserve_default=False,
        ),
    ]
