# Generated by Django 3.2.21 on 2023-09-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_vat_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
