version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8090:8090"
    volumes:
      - ./truck_app:/truck_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8090"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811ss
    depends_on:
      - db

  vue:
    build:
      context: ./truck_app/vue
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811ss

volumes:
  dev-db-data:
