version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8090:8090"
    volumes:
      - ./truck_app:/truck_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8090"

  vue:
    build:
      context: ./truck_app/vue
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on:
      - app
