version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8090:8090"
    volumes:
      - ./truck_app:/truck_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runsslserver 0.0.0.0:8090"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811ss
    depends_on:
      - db
    networks:
      - truckapp-network


  vue:
    build:
      context: ./truck_app/vue
      args:
        - DEV=true
    command: npm run serve
    ports:
      - "8095:8095"
    volumes:
      - ./truck_app/vue:/vue
      - /vue/node_modules
      - ./truck_app/vue/ssl:/vue/ssl
    depends_on:
      - app
    networks:
      - truckapp-network

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811ss
    networks:
      - truckapp-network

volumes:
  dev-db-data:

networks:
  truckapp-network:
    external: true
