# Generated by Django 3.2.21 on 2023-09-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceCode',
            new_name='MaintenanceGroup',
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
