# Generated by Django 3.2.21 on 2023-09-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20230917_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancegroup',
            name='jobs',
        ),
    ]
