# Generated by Django 3.2.21 on 2023-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenancegroup_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancegroup',
            name='jobs',
            field=models.ManyToManyField(to='maintenance.Job'),
        ),
    ]
