# Generated by Django 3.2.21 on 2023-09-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20230916_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
