# Generated by Django 3.2.21 on 2023-09-16 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0003_auto_20230916_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='last_edit_by',
        ),
        migrations.AddField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Last Edit By'),
        ),
    ]
