# Generated by Django 3.2.21 on 2023-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_alter_truck_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='body_style',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='transmission',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
