# Generated by Django 3.2.21 on 2023-09-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20230922_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(default='1', max_length=8)),
                ('date', models.DateField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
    ]
