# Generated by Django 3.2.21 on 2023-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=30)),
                ('adress_1', models.CharField(max_length=255, verbose_name='Street Adress')),
                ('city_town', models.CharField(max_length=255, verbose_name='City/Town')),
                ('province_state', models.CharField(max_length=255, verbose_name='State/Province/Region')),
                ('post_code', models.CharField(max_length=255, verbose_name='Postal Code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Company Loacations',
            },
        ),
    ]
